import turtle
wn = turtle.Screen()
wn.title("Star")
bob = turtle.Turtle()
bob.hideturtle()
bob.speed(5)
bob.goto(-150,0)
bob.color('blue', 'lightgreen')
bob.pensize(2)
bob.begin_fill()
n = int(input("Enter an odd integer greater than or equal to 3: "))
angle = -180+(180/n)
for i in range(n):
	bob.forward(300)
	bob.left(angle)
	bob.dot(10,"red")
bob.end_fill()
wn.mainloop()
done()